name: Build abschlussbericht with LaTeX
on: 
  push:
    branches: [ master ]
    paths: 
    - 'abschlussbericht/**'
    - '.github/workflows/abschlussberichtbuild.yml'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: abschlussbericht
      - name: Change filename
        run: cp abschlussbericht/main.pdf abschlussbericht.pdf
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: 'AbschlussBericht'
          path: 'abschlussbericht.pdf'