name: Build presentation with LaTeX Beamer
on: 
  push:
    branches: [ master ]
    paths: 
    - 'vortrag/**'
    - '.github/workflows/presentationbuild.yml'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: vortrag
      - name: Change filename
        run: cp vortrag/main.pdf bufferoverflow.pdf
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: 'BufferOverflow'
          path: 'bufferoverflow.pdf'